### ISSUE TITLE
Constant Reloading After Ublock/Google Changes to Ads

### ISSUE THREAD

**Issue by oven8Mitts** [JohnyP36/YT-Nonstop#22]
### Prerequisites

- [X] I've read the [Code of Conduct](https://github.com/JohnyP36/YT-Nonstop/blob/main/.github/CODE_OF_CONDUCT.md) and the [Contributing Guidelines](https://github.com/JohnyP36/YT-Nonstop/blob/main/.github/CONTRIBUTING.md)
- [X] I performed a [cursory search of the issue tracker](https://github.com/JohnyP36/YT-Nonstop/issues) to avoid opening a duplicate issue  *--  Your issue may already be reported.*
- [X] I am running the latest version of the extension

### I tried to reproduce the issue when...

- [X] Other webextensions related to Youtube are disabled  *-- Just to ensure there is no issues or conflicts with other webbrowser extensions.*
- [ ] using a new, unmodified browser profile

### Describe the issue

Getting reloading of the video as the page loads, occurs on every single page. Would occur about 50% of days since Google began blocking users who used Adblock. Now occurs every day. 

Console log entry when reloading:
`Could find play button; page got reloaded`
Disabling the YT Nonstop plugin fixes the reload issue.

### Browser & Extension version

Firefox 119.0 64bit

### Operating System & Version

Windows 10 22H2

### Notes

I use Sponsorblock, Ublock, and an older YT downloader plugin that isn't available anymore. I disabled all 3 to confirm no issues. Also verified anything like Tampermonkey is disabled.

**Comment by JohnyP36** [comment]
Hi @oven8Mitts. Thanks for your feedback.

Can you follow these steps and report what is happening.

1. Go to `www.youtube.com`
2. Open your console logger
3. Click on a random video on the homepage or search for one
4. Filter your console log on `YT Nonstop` and copy all messages (right mouse click on one of the log entries)

I got the following console log messages:
```txt
[YT Nonstop] 02:40:55 | Could find play button; page got reloaded     www.youtube.com:17:15
[YT Nonstop] 02:40:55 | Autoplay has been disabled     www.youtube.com:17:15
[YT Nonstop v2.0.9.2]                                  autoconfirm.js:48:9
[YT Nonstop] 02:41:03 | Autoplay has been disabled     watch:17:15
[YT Nonstop] 02:41:03 | Autoplay has been disabled     watch:17:15
[YT Nonstop] 02:41:08 | Autoplay has been disabled     watch:17:15
[YT Nonstop] 02:41:08 | Autoplay has been disabled     watch:17:15
[YT Nonstop] 02:41:13 | Autoplay has been disabled     watch:17:15
[YT Nonstop] 02:41:17 | Active Time Reset              watch:5:15
```

As you see I also got the `Couldn't find play button; page got reloaded`, but that occurs due to the fact that my extension was faster than Youtube got the video loaded. 
Normally this only happens the first time you go to YT and play a video, because if you reload the page (F5) the play button is already in the site code of YT and thus you will only get 3 console log messages
```txt
[YT Nonstop v2.0.9.2]                              autoconfirm.js:48:9
[YT Nonstop] 02:52:27 | Autoplay has been disabled watch:17:15
[YT Nonstop] 02:52:39 | Active Time Reset          watch:5:15
```

The above will also happen if you directly open a YT video by pasting a link (e.g. [`Shuffle Dance Music playlist`](https://www.youtube.com/watch?v=oOSLFr87tGo&list=PLLVTfyOzORL5r1pE6ru2Hs7np9zJWzh3y&index=1)) and also for Youtube Music.
*if you enabled loop playlist, you will also see the message `Playlist is been looped`.*

---

To keep a long story short: Although there have been many reports of Google/Youtube blocking users if they use Adblockers (see https://github.com/uBlockOrigin/uAssets/issues/19976 and **please also try what is suggested [there](https://github.com/uBlockOrigin/uAssets/issues/19976#issuecomment-1792441479)**) I never encountered this issue and whatever I try I can't reproduce your issue.

So, could you give me a detail outline of what is happening at your side and what you are seeing after each step?

**Comment by JohnyP36** [comment]
> I cannot reproduce at this time. 2.0.9.4. Perhaps there was a patch? Close the issue as needed. Thanks

I disabled the `try-and-catch` method. But the downside of this is that if the extension can't find the play button it will not work properly and you need to manually refresh the page. It's either constant reloading or possible not working properly. I can't fix both issues.
